"""documant model updated

Revision ID: 63fd05a7aaa8
Revises: 5cb39ca8edda
Create Date: 2025-12-25 00:00:26.438746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fd05a7aaa8'
down_revision: Union[str, Sequence[str], None] = '5cb39ca8edda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
